services:
  - type: worker
    name: ai-people-reader-worker
    env: python
    plan: standard
    region: singapore

    # Worker entry point
    startCommand: python src/worker.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

