services:
  - type: web
    name: App-maker-App-maker
    env: python
    region: oregon
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: streamlit run motion_web_app_full_dashboard_png.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: VIDEO1_URL
        value: "https://youtube.com/shorts/qpClWOkC2rw?si=N6yVCRrqxiJmOaSG"
      - key: VIDEO2_URL
        value: "https://youtube.com/shorts/qpClWOkC2rw?si=N6yVCRrqxiJmOaSG"
