services:
  - type: web
    name: App-maker-App-maker
    env: python
    region: oregon
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true

