services:
  - type: web
    name: App-maker-App-maker
    env: python
    region: oregon
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run motion_web_app_full_dashboard_png.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: VIDEO1_URL
        value: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      - key: VIDEO2_URL
        value: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    buildFilter:
      paths:
        - requirements.txt
        - motion_web_app_full_dashboard_png.py
        - .render.yaml
